blank_issues_enabled: false
contact_links:
  - name: Aurion IDE community on Discord
    url: https://discord.gg/n8tGJ6Rn6D
    about: Please ask and answer questions here.
  - name: Aurion IDE community on Matrix
    url: https://matrix.to/#/#Aurion IDE-editor:matrix.org
    about: Please ask and answer questions here.
  - name: Aurion IDE documentation
    url: https://docs.Aurion IDE.dev/
    about: Documentation for Aurion IDE



